name: Deploy Static Site to GitHub Pages

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify static site exists
        run: |
          if [ ! -d "static-site" ]; then
            echo "Error: static-site directory not found!"
            echo "Please generate the static site locally first using:"
            echo "  docker-compose up -d"
            echo "  npm run export"
            exit 1
          fi
          
          echo "Static site directory found. Contents:"
          ls -la static-site/
          
          # Verify essential files exist
          if [ ! -f "static-site/index.html" ]; then
            echo "Error: index.html not found in static-site directory!"
            exit 1
          fi
          
          if [ ! -f "static-site/CNAME" ]; then
            echo "Warning: CNAME file not found, creating one for www.kevops.co.uk"
            echo "www.kevops.co.uk" > static-site/CNAME
          fi
          
          if [ ! -f "static-site/.nojekyll" ]; then
            echo "Creating .nojekyll file for GitHub Pages"
            touch static-site/.nojekyll
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './static-site'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4